name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  auto-deploy:
    if: ${{ github.event.repository.fork == false }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 3

    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      SERVER: ${{ secrets.SERVER }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: bash .github/scripts/auto-deploy.sh
